name: MoveOrDie
main: ru.start.Plugin
api-version: 1.15
version: 0.1 Alpha
commands:
  gm:
    description: Fast gamemode switch
    usage: /gm [0-3]
  test:
    description: Test command, debug
    usage: /test
  lobby:
    description: Return to lobby spawn point
    usage: /lobby
  moveordie:
    description: Move or die (op) commands
    usage: /moveordie
    aliases: md